In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
url = r"C:\Users\User\Adult-Census-Income-Prediction\Eda and Dataset\adult.csv"

In [3]:
df=pd.read_csv(url)

In [4]:
df.drop(['education','marital-status','relationship','race','occupation','country'],axis = 1,inplace=True)

In [5]:
X=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [6]:
X.head()

age          workclass  fnlwgt  education-num      sex  capital-gain  \
0   39          State-gov   77516             13     Male          2174   
1   50   Self-emp-not-inc   83311             13     Male             0   
2   38            Private  215646              9     Male             0   
3   53            Private  234721              7     Male             0   
4   28            Private  338409             13   Female             0   

   capital-loss  hours-per-week  
0             0              40  
1             0              13  
2             0              40  
3             0              40  
4             0              40

In [7]:
y.head()

0     <=50K
1     <=50K
2     <=50K
3     <=50K
4     <=50K
Name: salary, dtype: object

In [8]:
Workclass =pd.get_dummies(X['workclass'],drop_first=True)
Sex=pd.get_dummies(X['sex'],drop_first=True)

In [12]:
X=X.drop(['workclass','sex'],axis=1)

In [13]:
X=pd.concat([X,Workclass,Sex],axis=1)

In [14]:
X.head()

age  fnlwgt  education-num  capital-gain  capital-loss  hours-per-week  \
0   39   77516             13          2174             0              40   
1   50   83311             13             0             0              13   
2   38  215646              9             0             0              40   
3   53  234721              7             0             0              40   
4   28  338409             13             0             0              40   

    Federal-gov   Local-gov   Never-worked   Private   Self-emp-inc  \
0             0           0              0         0              0   
1             0           0              0         0              0   
2             0           0              0         1              0   
3             0           0              0         1              0   
4             0           0              0         1              0   

    Self-emp-not-inc   State-gov   Without-pay   Male  
0                  0           1             0      1  
1                  1           0             0      1  
2                  0           0             0      1  
3                  0           0             0      1  
4                  0           0             0      0

In [19]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [20]:
from sklearn.preprocessing import StandardScaler
sc =StandardScaler()
X_train=sc.fit_transform(X_train)
X_test =sc.transform(X_test)

In [21]:
X_train

array([[-0.40875606,  0.08005085,  1.13370219, ..., -0.20433629,
        -0.0195973 , -1.41882738],
       [-0.1888573 , -0.98165286,  0.35704925, ..., -0.20433629,
        -0.0195973 ,  0.70480737],
       [ 1.42373357,  0.126197  , -1.97290957, ..., -0.20433629,
        -0.0195973 ,  0.70480737],
       ...,
       [-1.50824984,  0.25206312, -1.19625663, ..., -0.20433629,
        -0.0195973 , -1.41882738],
       [ 0.83733689, -1.28762772, -0.41960369, ..., -0.20433629,
        -0.0195973 ,  0.70480737],
       [-0.33545648, -0.59020877,  1.13370219, ..., -0.20433629,
        -0.0195973 ,  0.70480737]])

In [22]:
X_test

array([[-0.84855357, -0.28110745, -0.03127722, ..., -0.20433629,
        -0.0195973 , -1.41882738],
       [ 0.47083896, -1.32273149, -0.41960369, ...,  4.89389329,
        -0.0195973 , -1.41882738],
       [-0.7019544 , -0.03659744,  1.13370219, ..., -0.20433629,
        -0.0195973 ,  0.70480737],
       ...,
       [ 0.61743814,  1.56217302,  1.91035513, ..., -0.20433629,
        -0.0195973 ,  0.70480737],
       [-0.84855357, -1.38844415,  1.13370219, ..., -0.20433629,
        -0.0195973 , -1.41882738],
       [-1.50824984, -1.55773858, -0.41960369, ..., -0.20433629,
        -0.0195973 ,  0.70480737]])

In [37]:
from sklearn.linear_model import LogisticRegression
regression=LogisticRegression()

In [38]:
from sklearn.model_selection import GridSearchCV

parameter={'C':[0.5,1,2,3,5,6,7,9,10,30,45],'penalty':['l1','l2','elasticnet']}
log_regressor=GridSearchCV(regression,parameter,scoring='accuracy',cv=5)

log_regressor.fit(X,y)

c:\Users\User\Adult-Census-Income-Prediction\venv\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning: 
110 fits failed out of a total of 165.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
55 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\User\Adult-Census-Income-Prediction\venv\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\User\Adult-Census-Income-Prediction\venv\lib\site-packages\sklearn\linear_model\_logistic.py", line 1461, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "c:\Users\User\Adult-Census-Income-Prediction\venv\lib\s

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [0.5, 1, 2, 3, 5, 6, 7, 9, 10, 30, 45],
                         'penalty': ['l1', 'l2', 'elasticnet']},
             scoring='accuracy')

In [39]:
print(log_regressor.best_params_)

{'C': 0.5, 'penalty': 'l2'}


In [40]:
print(log_regressor.best_score_)

0.7975799582087008


In [41]:
prediction_log=log_regressor.predict(X_test)

c:\Users\User\Adult-Census-Income-Prediction\venv\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  "X does not have valid feature names, but"


In [42]:
from sklearn.metrics import accuracy_score,confusion_matrix,precision_recall_curve,roc_auc_score,f1_score

In [43]:
confusion_matrix(y_test,prediction_log)

array([[4760,  182],
       [1105,  466]], dtype=int64)

In [44]:
accuracy_score(y_test,prediction_log)

0.8023952095808383

In [32]:
from sklearn.ensemble import RandomForestClassifier


In [33]:
clf = RandomForestClassifier(n_estimators = 100)
clf.fit(X_train, y_train)

RandomForestClassifier()

In [34]:
y_pred = clf.predict(X_test)

In [35]:
from sklearn import metrics 
print()

In [36]:
print("ACCURACY OF THE MODEL: ", metrics.accuracy_score(y_test, y_pred))

ACCURACY OF THE MODEL:  0.8252725318593582


In [45]:
from sklearn.svm import SVC

In [46]:
svc_model = SVC(C= .1, kernel='linear', gamma= 1)
svc_model.fit(X_train, y_train)

SVC(C=0.1, gamma=1, kernel='linear')

In [47]:
prediction = svc_model .predict(X_test)

In [48]:
print(svc_model.score(X_train, y_train))
print(svc_model.score(X_test, y_test))

0.8146882678132679
0.8189774297558728


In [49]:
print("Confusion Matrix:\n",confusion_matrix(prediction,y_test))

Confusion Matrix:
 [[4819 1056]
 [ 123  515]]


In [50]:
from sklearn.ensemble import GradientBoostingClassifier

In [51]:
clf = GradientBoostingClassifier(n_estimators=100, learning_rate=1.0,max_depth=1, random_state=0).fit(X_train, y_train)

In [52]:
clf.score(X_test, y_test)

0.8472286196837095

In [53]:
clf.score(X_train, y_train)

0.8468212530712531